<?php
/**
 * Страница "Форма редактирования IP-адреса".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Форма добавления / редактирования IP-адреса</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Добавить"</b> панели инструментов списка IP-адресов или выбора пункта <b>"Редактировать"</b> контекстного меню выбранной записи.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><b>IP-адрес / Маска.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Описание.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>IP-адрес доступен для Панели управления.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>IP-адрес доступен для Сайта.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
    </ul>
</article>